---
resources:
  - name: code
    type: git
    source: 
      uri: https://github.com/yamikarajput546/capstoneconcourse
      branch: main

jobs:
  - name: compile
    plan: 
      - get: code
        trigger: true
      - task: clean
        config: 
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: maven
          inputs:
            - name: code
          run: 
            path: mvn
            args: 
              - clean
              - -f
              - code/pom.xml 